sudo: required
language: cpp
matrix:
  fast_finish: true
  include:
# Debug builds on both MacOS and Linux
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - NAME="Mac [dbg/clang]" CMAKE_BUILD_TYPE=debug TPL_USE_ASAN=On
      install:
        - echo 'y' | ./deps.sh
        - export PATH=/usr/local/opt/llvm/bin:$PATH
    - os: linux
      dist: trusty
      env:
        - NAME="Docker[dbg/packages.sh]" CMAKE_BUILD_TYPE=debug TPL_USE_ASAN=On DOCKER=true
      install:
        - docker pull ubuntu:18.04
        - docker run -itd --name build ubuntu:18.04
        - docker cp . build:/repo
        - docker exec build /bin/sh -c "echo 'y' | /repo/deps.sh"
# Release builds. Will be replaced by Jenkins
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - NAME="Mac [rel/clang]" CMAKE_BUILD_TYPE=release TPL_USE_ASAN=Off
      install:
        - echo 'y' | ./deps.sh
        - export PATH=/usr/local/opt/llvm/bin:$PATH
    - os: linux
      dist: trusty
      env:
       - NAME="Docker[rel/packages.sh]" CMAKE_BUILD_TYPE=release TPL_USE_ASAN=Off DOCKER=true
      install:
        - docker pull ubuntu:18.04
        - docker run -itd --name build ubuntu:18.04
        - docker cp . build:/repo
        - docker exec build /bin/sh -c "echo 'y' | /repo/deps.sh"

before_script:
  - if [[ "$DOCKER" = true ]]; then
      docker exec build /bin/sh -c "mkdir -p /repo/build" &&
      docker exec -e CMAKE_CXX_FLAGS="-mavx2" CMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" -e TPL_USE_ASAN="$TPL_USE_ASAN" build /bin/sh -c "cd /repo/build && cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DTPL_USE_ASAN=$TERRIER_USE_ASAN .." &&
      docker exec build /bin/sh -c "cd /repo/build && make check-clang-tidy" &&
      docker exec build /bin/sh -c "cd /repo/build && make check-format" &&
      docker exec build /bin/sh -c "cd /repo/build && make check-lint" &&
      docker exec build /bin/sh -c "cd /repo/build && make check-censored";
    else
      mkdir build &&
      cd build &&
      cmake -DCMAKE_CXX_FLAGS="-mavx2" -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DTPL_USE_ASAN=$TPL_USE_ASAN .. &&
      ASAN_OPTIONS=detect_container_overflow=0 make check-clang-tidy &&
      ASAN_OPTIONS=detect_container_overflow=0 make check-format &&
      ASAN_OPTIONS=detect_container_overflow=0 make check-lint &&
      ASAN_OPTIONS=detect_container_overflow=0 make check-censored;
    fi

script:
  - if [[ "$DOCKER" = true ]]; then
      docker exec build /bin/sh -c "cd /repo/build && make" &&
      docker exec build /bin/sh -c "cd /repo/build && make check" ;
    else
      ASAN_OPTIONS=detect_container_overflow=0 make &&
      ASAN_OPTIONS=detect_container_overflow=0 make check ;
    fi
