name: CMake CI

on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Instal CMake
      uses: lukka/get-cmake@latest

    - name: Cleanup Environment
      run: |
        # Add LLVM 11 repositories.
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
        sudo apt update

        # Remove previous versions of Clang/LLVM.
        sudo apt-get remove -y clang-8 clang-9 clang-format-8 clang-format-9 clang-tidy-8 clang-tidy-9 llvm-8 llvm-9
        sudo apt-get purge
        sudo apt-get autoremove

    - name: Install Dependencies
      run: |
        echo y | sudo ./deps.sh

    - name: Check Formatting
      env:
        CC: gcc-10
        CXX: g++-10
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DTPL_USE_ASAN=On
        cd build
        ninja check-format

    - name: Build & Test Debug x64 With Sanitizers
      env:
        CC: gcc-10
        CXX: g++-10
        LSAN_OPTIONS: "fast_unwind_on_malloc=0,suppressions=${{github.workspace}}/build-support/leaksanitizer.conf"
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DTPL_USE_ASAN=On
        cd build
        LSAN_OPTIONS=$LSAN_OPTIONS ninja
        LSAN_OPTIONS=$LSAN_OPTIONS ninja check
        # Disable check-tpl because LLVM compilation on VM's is super slow!
        #LSAN_OPTIONS=$LSAN_OPTIONS ninja check-tpl

    - name: Build & Test Release x64
      env:
        CC: gcc-10
        CXX: g++-10
        LSAN_OPTIONS: "fast_unwind_on_malloc=0,suppressions=${{github.workspace}}/build-support/leaksanitizer.conf"
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -GNinja -DCMAKE_BUILD_TYPE=Release
        cd build
        # Maybe run benchmarks, too?
        LSAN_OPTIONS=$LSAN_OPTIONS ninja
        LSAN_OPTIONS=$LSAN_OPTIONS ninja check-tpl

    - name: Generate & Upload Code Coverage Report
      env:
        CC: gcc-10
        CXX: g++-10
        LSAN_OPTIONS: "fast_unwind_on_malloc=0,suppressions=${{github.workspace}}/build-support/leaksanitizer.conf"
      run: |
        cmake -E remove_directory build
        cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DTPL_USE_ASAN=On -DTPL_GENERATE_COVERAGE=On
        cd build
        LSAN_OPTIONS=$LSAN_OPTIONS ninja
        LSAN_OPTIONS=$LSAN_OPTIONS ninja check
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info --output-file coverage.info \
             '/usr/*'                                           \
             '*/build/*'                                        \
             '*/third_party/*'                                  \
             '*/benchmark/*'                                    \
             '*/test/*'                                         \
             '*/src/tpl.cpp'
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -X gcov
