name: CMake CI

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        # LLVM 9 is not in Bionic's repositories so we add the official LLVM repository.
        sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt-get update

        # Remove previous versions of Clang tools.
        sudo apt-get remove -y clang-6.0 clang-7 clang-8 clang-format-6.0 clang-format-7 clang-format-8 clang-tidy-8 llvm-6.0 llvm-7 llvm-8 libllvm6.0 libllvm7 libllvm8
        sudo apt-get purge
        sudo apt-get autoremove

        # Install dependencies.
        echo y | sudo ./deps.sh

        # Configure system.
        echo "::set-env name=CC::gcc-9"
        echo "::set-env name=CXX::g++-9"

    - name: Build & Test Debug x64 With Sanitizers
      run: |
        cmake -E remove_directory build
        LLVM_DIR=/usr/lib/llvm-9/ cmake -B build -S . -GNinja -DCMAKE_BUILD_TYPE=Debug -DTPL_USE_ASAN=On
        cmake --build build -j$(nproc)
        cd build
        LSAN_OPTIONS="fast_unwind_on_malloc=0,suppressions=$GITHUB_WORKSPACE/build-support/leaksanitizer.conf" ninja
        LSAN_OPTIONS="fast_unwind_on_malloc=0,suppressions=$GITHUB_WORKSPACE/build-support/leaksanitizer.conf" ninja check
        LSAN_OPTIONS="fast_unwind_on_malloc=0,suppressions=$GITHUB_WORKSPACE/build-support/leaksanitizer.conf" ninja check-tpl

    - name: Build & Test Release x64
      run: |
        cmake -E remove_directory build
        LLVM_DIR=/usr/lib/llvm-9/ cmake -B build -S . -GNinja -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j$(nproc)
        cd build
        LSAN_OPTIONS="fast_unwind_on_malloc=0,suppressions=$GITHUB_WORKSPACE/build-support/leaksanitizer.conf" ninja
        LSAN_OPTIONS="fast_unwind_on_malloc=0,suppressions=$GITHUB_WORKSPACE/build-support/leaksanitizer.conf" ninja check-tpl